




.build/mega2560/src/acr_control.cpp : src/acr_control.ino
	@mkdir -p .build/mega2560/src
	@echo [93msrc/acr_control.ino[0m
	@/usr/local/bin/ino preproc  -o $@ $^


all : .build/mega2560/src/acr_control.cpp
	@true

